# Generated by Django 3.0.4 on 2020-07-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
